version: '3.3'
services:
  n8n:
    
    image: n8n
    build: 

      context: .
    ports: 
      - "5678:5678"
    network_mode: bridge
    volumes:
      - ./n8n:/root/.n8n
    
    deploy:
      resources:
        limits:
          memory: 1000m
          cpus: "1"
        reservations:
          memory: 500m

      
